# Generated by Django 4.1.6 on 2023-02-07 02:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listing_watching_delete_watching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watching',
            field=models.ManyToManyField(blank=True, related_name='watchers', to=settings.AUTH_USER_MODEL),
        ),
    ]
